name: Deploy AWS SAM Application

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  AWS_REGION: us-east-1 # Cambia esto si usas otra región
  # S3_BUCKET: s3-project-1-test-fede-admin # Definir como secreto en GitHub
  STACK_NAME: basic-stack-generate-sam # Definir como secreto en GitHub
  SAM_TEMPLATE: template.yml
  PIPELINE_EXECUTION_ROLE: arn:aws:iam::532353884571:role/PIPELINE_EXECUTION_ROLE

jobs:
  deploy-dev:
    if: github.event_name == 'push' && startsWith(github.ref,'refs/heads/develop')
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      # Step 1: Checkout the code
      - name: STEP1-Checkout code
        uses: actions/checkout@v3

      # Step 2: Configurar SAM
      - name: STEP2-Setup SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      #Step 3: hacer el build de SAM a ClodFormation
      - name: STEP3-Build template SAM
        run: sam build --template ${SAM_TEMPLATE} --use-container

      - name: STEP4-Assume the testing pipeline user role
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.PIPELINE_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PIPELINE_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.PIPELINE_EXECUTION_ROLE }}
          role-session-name: feature-deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      # Step 5: Deploy SAM stack
      - name: STEP5-Deploy SAM Application
        run: |
          sam deploy --stack-name ${STACK_NAME} \
            --template template.yml \
            --capabilities CAPABILITY_IAM \
            --region ${AWS_REGION} \
            --s3-bucket project-1-aws-fede-128937 \
            --no-fail-on-empty-changeset \
            --role-arn arn:aws:iam::532353884571:role/CLOUDFORMATION_ROL
